---
- name: Reboot systems
  hosts: all
  become: true
  serial: "{{ osism_serial['reboot']|default('1') }}"

  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to reboot the systems?
      default: 'no'
      private: no

  tasks:
    - name: Exit playbook, if user did not mean to reboot systems
      fail:
        msg: >
          "To reboot the systems, either say 'yes' on the prompt or
           use `-e ireallymeanit=yes` on the command line when
           invoking the playbook"
      when: ireallymeanit != 'yes'

    - name: Reboot system
      shell: sleep 2 && /sbin/shutdown -r now
      async: 1
      poll: 0
