---
- name: Reboot systems
  hosts: all
  serial: "{{ osism_serial['reboot']|default('1') }}"
  strategy: "{{ osism_strategy|default('linear') }}"

  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to reboot the systems?
      default: 'no'
      private: false

  tasks:
    - name: Exit playbook, if user did not mean to reboot systems
      fail:
        msg: >
          "To reboot the systems, either say 'yes' on the prompt or
           use `-e ireallymeanit=yes` on the command line when
           invoking the playbook"
      when: ireallymeanit != 'yes'

    - name: Reboot system
      become: true
      reboot:
