---
- name: Apply role docker_compose
  hosts: "{{ hosts_docker|default('docker') }}"
  serial: "{{ osism_serial['docker_compose']|default('0') }}"
  strategy: "{{ osism_strategy|default('linear') }}"

  collections:
    - osism.commons

  roles:
    - role: docker_compose
