---
- hosts: mirror

  tasks:
  - name: Include images file
    include_vars:
      file: "{{ docker_images_file }}"

  - name: Include images file as images variable
    include_vars:
      file: "{{ docker_images_file }}"
      name: images

  - name: Prepare internal images
    set_fact:
      _images_internal: |
        {% for image in images %}
        {{ image }}: {{ images[image] }}
        {% endfor %}
    vars:
      docker_registry: "{{ docker_registry_internal }}"

  - name: Finalize internal images
    set_fact:
      images_internal: "{{ _images_internal|from_yaml }}"

  - name: Prepare external images
    set_fact:
      _images_external: |
        {% for image in images %}
        {{ image }}: {{ images[image] }}
        {% endfor %}
    vars:
      docker_registry: "{{ docker_registry_external }}"

  - name: Finalize external images
    set_fact:
      images_external: "{{ _images_external|from_yaml }}"

  - name: Include tasks to transfer a image
    include: tasks/infrastructure-mirror-image.yml image="{{ item.key }}" tag="{{ item.key|replace('_image', '_tag') }}"
    when: "'_image' in item.key and '_image_tag' not in item.key"
    with_dict: "{{ images_external }}"
