---
- name: Confirm whether user really meant to purge the cluster
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to purge the cluster?
      default: 'no'
      private: false

  tasks:
    - name: Exit playbook, if user did not mean to purge cluster
      ansible.builtin.fail:
        msg: >
          "Exiting rook-purge playbook, cluster was NOT purged.
           To purge the cluster, either say 'yes' on the prompt or
           or use `-e ireallymeanit=yes` on the command line when
           invoking the playbook"
      when: ireallymeanit != 'yes'

- name: Purge Ceph cluster managed with Rook
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local
  gather_facts: false

  tasks:
    - name: Include cleanup.yml from osism.services.rook role
      ansible.builtin.include_role:
        name: osism.services.rook
        tasks_from: cleanup.yml
